---
__php_packages:
  - php5.6-common
  - php5.6-cli
  - php5.6-dev
  - php5.6-fpm
  - libpcre3-dev
  - php5.6-gd
  - php5.6-curl
  - php5.6-imap
  - php5.6-json
  - php5.6-opcache
  - php5.6-xml
  - php5.6-mbstring
  - php5.6-mysql
  - php5.6-mcrypt
  - php5.6-zip
  - php-sqlite3
  - php-apcu
__php_webserver_daemon: "apache2"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths:
  - /etc/php/5.6/fpm
  - /etc/php/5.6/apache2
  - /etc/php/5.6/cli

__php_extension_conf_paths:
  - /etc/php/5.6/fpm/conf.d
  - /etc/php/5.6/apache2/conf.d
  - /etc/php/5.6/cli/conf.d

__php_apc_conf_filename: 20-apcu.ini
__php_opcache_conf_filename: 05-opcache.ini
__php_fpm_daemon: php5.6-fpm
__php_fpm_conf_path: "/etc/php/5.6/fpm"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data
