---
server_runs_as: "www-data"
server_runs_as_group: "www-data"

  # Joomla config variable
joomla_offline : "0"
joomla_offline_message : "This site is down for maintenance.<br />Please check back again soon."
joomla_display_offline_message : "1"
joomla_offline_image : ""
joomla_sitename : ""
joomla_editor : "tinymce"
joomla_captcha : "0"
joomla_list_limit : "20"
joomla_access : "1"
joomla_debug : "0"
joomla_debug_lang : "0"
joomla_dbtype : "mysqli"
joomla_live_site : ""
joomla_secret : ""
joomla_gzip : "0"
joomla_error_reporting : "none"
joomla_helpurl : "https://help.joomla.org/proxy/index.php?keyref:Help{major}{minor}:{keyref}"
joomla_ftp_host : "127.0.0.1"
joomla_ftp_port : "21"
joomla_ftp_user : ""
joomla_ftp_pass : ""
joomla_ftp_root : ""
joomla_ftp_enable : "0"
joomla_offset : "UTC"
joomla_mailonline : "1"
joomla_mailer : "mail"
joomla_mailfrom : ""
joomla_fromname : ""
joomla_sendmail : "/usr/sbin/sendmail"
joomla_smtpauth : "0"
joomla_smtpsecure : "none"
joomla_smtpport : "25"
joomla_caching : "0"
joomla_cache_handler : "file"
joomla_cachetime : "15"
joomla_cache_platformprefix : "0"
joomla_MetaDesc : ""
joomla_MetaKeys : ""
joomla_MetaTitle : "1"
joomla_MetaAuthor : "1"
joomla_MetaVersion : "0"
joomla_robots : "noindex, nofollow"
joomla_sef : "1"
joomla_sef_rewrite : "0"
joomla_sef_suffix : "0"
joomla_unicodeslugs : "0"
joomla_feed_limit : "10"
joomla_feed_email : "none"
joomla_log_path : ""
joomla_tmp_path : ""
joomla_lifetime : "180"
joomla_session_handler : "database"
joomla_memcache_persist : "1"
joomla_memcache_compress : "0"
joomla_memcache_server_host : "localhost"
joomla_memcache_server_port : "11211"
joomla_memcached_persist : "1"
joomla_memcached_compress : "0"
joomla_memcached_server_host : "localhost"
joomla_memcached_server_port : "11211"
joomla_redis_persist : "1"
joomla_redis_server_host : "localhost"
joomla_redis_server_port : "6379"
joomla_redis_server_auth : ""
joomla_redis_server_db : "0"
joomla_proxy_enable : "0"
joomla_proxy_host : ""
joomla_proxy_port : ""
joomla_proxy_user : ""
joomla_proxy_pass : ""
joomla_massmailoff : "0"
joomla_MetaRights : ""
joomla_sitename_pagetitles : "0"
joomla_force_ssl : "2"
joomla_session_memcache_server_host : "localhost"
joomla_session_memcache_server_port : "11211"
joomla_session_memcached_server_host : "localhost"
joomla_session_memcached_server_port : "11211"
joomla_frontediting : "1"
joomla_cookie_domain : ""
joomla_cookie_path : ""
joomla_asset_id : "1"

# Cron list
cron_list: []