---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: selinux support under EL 6
  yum: name=libselinux-python state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Install OCS inventory agent on RedHat OS family
  yum: name={{ ocsinventory_package_name }} state=present enablerepo={{ ocsinventory_yum_repository }}
  notify: Launch ocs inventory
  when: ansible_os_family == "RedHat"

- name: Install OCS inventory agent on Debian OS family
  apt: name={{ ocsinventory_package_name }} state=present default_release={{ ocsinventory_apt_target_release }}
  notify: Launch ocs inventory
  when: ansible_os_family == "Debian"

- name: Remove default local option from ocsinventory-agent.cfg
  lineinfile: dest=/etc/ocsinventory/ocsinventory-agent.cfg
              regexp="^local = "
              state=absent

- name: Configure CRON job
  cron: name="{{ ocsinventory_cronjob_name }}"
        user="{{ ocsinventory_cronjob_user }}"
        month="{{ ocsinventory_cronjob_month }}"
        weekday="{{ ocsinventory_cronjob_weekday }}"
        day="{{ ocsinventory_cronjob_day }}"
        hour="{{ ocsinventory_cronjob_hour }}"
        minute="{{ ocsinventory_cronjob_minute }}"
        job="{{ocsinventory_binary}} {{ocsinventory_launch_options}}"
  when: ocsinventory_setup_cronjob

